### ISSUE TITLE
Include ADC quad-core calibration as part of R2DBE startup

### ISSUE THREAD

**Issue by anyoung** [sma-wideband/r2dbe#1]
Implementation may include:
1) bitcode changes to support this, e.g. long-term histograms on 8-bit data
2) software development to solve for ADC parameters
3) system for logging / applying solutions

@lindyblackburn

**Comment by lindyblackburn** [comment]
The following code was used for ADC calibration in 2015, 2016

https://github.com/sao-eht/lmtscripts/blob/master/og.py

It would be good to have 8-bit histogram support before merging this functionality into the standard R2DBE libraries.
