### ISSUE TITLE
Allow r2dbe_start.py to run from outside software directory

### ISSUE THREAD

**Issue by lindyblackburn** [sma-wideband/r2dbe#5]
r2dbe_start.py calls alc.py, which must live in the current working directory. This means r2dbe_start.py must be run from the software directory. It's often more convenient to run r2dbe_start.py from some other location, such as the location where the site-specific configuration file lives.

**Comment by anyoung** [comment]
Startup (and other scripts) are now executable from outside the software directory in the control computer standard backend configuration
