### ISSUE TITLE
Remove hard-coded IP addresses in R2DBE switch scripts

### ISSUE THREAD

**Issue by lindyblackburn** [sma-wideband/r2dbe#6]
A number of noise-box control scripts contain hard-coded IP addresses which must be edited for each site. This causes the site-specific r2dbe repository to be in conflict with maser. If the IP address can be moved to the configuration file, it will be possible to keep these scripts consistent with maser.

switch_get_status.py
switch_set_IF.py
switch_set_noise.py

**Comment by anyoung** [comment]
Switch no longer part of standard backend configuration
